<div class="row">
   <div class="col-sm-3"></div> 
   <div class="col-sm-6 col-xs-12">
       <?php echo Form::open() ?>
            <label>Correo</label>
			<?php echo Form::text('correo', 'class="form-control" placeholder="ejemplo@gmail.com"') ?>
            <br/>
			<?php echo Form::submit('Registrar cliente en el sistema', 'class="btn btn-primary form-control"') ?>
       <?php echo Form::close() ?>
   </div>
   <div class="col-sm-3"></div>
</div>