<div class="row">
	<div class="col-sm-3"></div>
	<div class="col-xs-12 col-sm-6">
		<h2 class="text-center">Iniciar sesión en el sistema</h2>
		<?php View::content() ?>
		<?php echo Form::open() ?>
		<div class="form-group">
		<input name="mode" type="hidden" value="auth">	
		<label>Correo</label>
			<?php echo Form::text('correo', 'class="form-control" placeholder="ejemplo@gmail.com"') ?>
		<label>Clave</label>
			<?php echo Form::pass('clave', 'class="form-control" placeholder="****"') ?>
			<br/>
			<?php echo Form::submit('Entrar al sistema', 'class="btn btn-success form-control"') ?>
		</div>
		<?php echo Form::close() ?>
	</div>
	<div class="col-sm-3"></div>
</div>
