<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-xs-12 col-sm-6">
        <h4 class="text-center">Administración de la web</h4>
        <p>Bienvenido: <?php echo $nombre; ?></p>
        <?php echo Html::link('noticias', 'Ir al módulo de noticias', 'class="btn btn-success"') ?>
        <br/>
    </div>
    <div class="col-sm-3"></div>
</div>
<div class="row">
	<div class="col-sm-3"></div>
	<div class="col-xs-12 col-sm-6">
		<?php echo Html::link('administrador/cerrar', 'Cerrar Sesión', 'class="btn btn-danger"') ?>
	</div>
	<div class="col-sm-3"></div>
</div>
