<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6 col-xs-12">
    <?php View::content(); ?>
    <?php echo Form::openMultipart() ?>
		<div class="form-group">
			<label>Titulo</label>
			<?php echo Form::text('titulo', 'class="form-control"', $noticias->titulo) ?>
			<label>Contenido</label>
			<?php echo Form::textarea('contenido', 'class="form-control"', $noticias->contenido) ?>
			<label>Imagen</label>
			<?php echo Form::file('imagen', NULL) ?>
      <?php echo Form::hidden('id', NULL, $noticias->id) ?>
			<br/>
			<?php echo Form::submit('Editar noticia', 'class="form-control btn btn-primary"') ?>
		</div>
		<?php echo Form::close() ?>
	<?php echo Html::link('noticias', 'Panel de noticias', 'class="btn btn-success"') ?>
    <?php echo Html::link('administrador/inicio', 'Panel de clientes', 'class="btn btn-primary"') ?>
  </div>
  <div class="col-sm-3"></div>
</div>