<div class="jumbotron">
  <h1>Yickson Ramírez</h1>
  <p>Soy un desarrollador web apasionado por la tecnología, así como por el aprendizaje constante de las mismas
  como lo son PHP, MySQL, Javascript, Jquery, HTML5, CSS3, Ruby on Rails, algunos framework de PHP como lo son:
  KumbiaPHP, Laravel, así como otras herramientas que van saliendo para impulsar el crecimiento de la web.</p>
  <p><a class="btn btn-primary btn-lg" href="inicio/contacto">Contratame</a></p>
</div>
<div class="col-md-4 col-xs-12">
  <div class="card">
  <?php echo Html::img('avatar.png', 'Perfil', 'class="imagen" style="width:100%"') ?>
  <div class="contenedor">
    <h4><b>Yickson Ramírez</b></h4>
    <p>Ingeniero en sistemas - System Engineering</p>
    <p><strong>Desarrollador web - Web Developer</strong></p>
  </div>
</div>
</div>
<div class="col-md-8 col-xs-12">
  <h3 class="text-center">¿Por qué deberías contratarme?</h3>
  <p>
    Si me contratas tendrás a una persona motivada y comunicativa, con los proyectos que quieras desarrollar, de forma
    que tenerme en tu equipo/empresa aumentará significativamente el desempeño de las ideas que tengas, y quieras emprender,
    así como alguien que quiere aprender de todo lo referente al hermoso e increíble mundo de la tecnología.
  </p>
  <p>He tenido mucha experiencia en varias empresas desarrollando y apoyando diferentes tipos de proyectos como lo son:</p>
  <ul>
    <li>Administración de sitios web realizados en CMS como WordPress, Joomla</li>
    <li>Desarrollo de aplicaciones sencillas para sustituir a Excel</li>
    <li>Desarrollo de aplicaciones web complejas en Framework de PHP</li>
    <li>Gestión de bases de datos</li>
    <li>Apoyo en soporte técnico</li>
    <li>Dominio de sistemas operativos libres como lo son Ubuntu, Fedora, Peppermint, Lubuntu</li>
  </ul>
  <p>Siempre busco soluciones sencillas para los problemas de sistemas, aparte de que siempre te tendré informado de los
  avances del proyecto por medio de informes específicos, a pesar de tener nacionalidad chilena, soy venezolano de nacimiento
por lo que trabajaré el doble para demostrar mi valía en el cargo que desempeñe.</p>
</div>
