<div class="row">
    <h2 class="text-center">Contacto</h2>
    <div class="col-xs-12 col-sm-6">
        <?php View::content(); ?>
        <div class="well">
            <?php echo Form::open('', 'post') ?>
            <fieldset>
            <div class="form-group">
            <label>Empresa</label>
            <?php echo Form::text('nombre', 'class="form-control" required') ?>
            <label>Correo</label>
            <?php echo Form::text('correo', 'class="form-control" required') ?>
            <label>Motivo</label>
            <?php echo Form::textarea('motivo', 'class="form-control"') ?>
            <br />
            <?php echo Form::submit('Enviar', 'class="btn btn-success"') ?>
            </div>
            </fieldset>
            <?php echo Form::close(); ?>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">Información importante</h3>
          </div>
          <div class="panel-body">
            <p>Si estás llenando este formulario para otorgarme una entrevista de trabajo entonces con todo el gusto asistiré
            el día y la hora del lugar.</p>
            <p>
              También puedes comunicarte conmigo a través de mi correo sistemas@yickson.com.ve para responderte a la brevedad posible.
            </p>
          </div>
        </div>
    </div>
</div>
