<div class="col-lg-2"></div>
<div class="col-lg-8">
  <ul class="nav nav-tabs">
  <li class="active"><a href="#inicio" data-toggle="tab" aria-expanded="true">Comienzo</a></li>
  <li class=""><a href="#profile" data-toggle="tab" aria-expanded="false">Experiencia Laborales</a></li>
  <li class=""><a href="#finales" data-toggle="tab" aria-expanded="false">Mi repertorio web</a></li>
</ul>
<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade active in" id="inicio">
    <p>Mis estudios de Ingeniería en sistemas comenzaron en la Universidad Bicentenaria de Aragua, aprendiendo lo básico de la programación así como la parte de redes
    luego de eso fui realizando diferentes cursos, como ensamble de computadoras de escritorios, Excel avanzado, Access básico, Manejo de Base de datos con PostgreSQL,
  programación estructurada con PHP y MySQL, HTML y CSS, así como otros conocimientos los adquirí a través de Internet realizando diferentes cursos online.</p>
  </div>
  <div class="tab-pane fade" id="profile">
    <p>Mi perfil esta orientado a la construcción de sitios web en PHP y MySQL, sin embargo he tenido la oportunidad de colaborar en proyectos basados en Ruby on Rails,
    con base de datos en SQLite aprendiendo los potenciales de este framework, los framework que he trabajado y manejado constantemente son Laravel, KumbiaPHP, de hecho
  este sitio esta realizado en KumbiaPHP, los sitios web que he construido manejan un Front-end que es la parte que el usuario ve e interactúa así como un Backend para
administrar la aplicación web en caso de que quiera un gestor de contenido.</p>
<p>
  En el año 2012 tuve la grandiosa oportunidad de trabajar como pasante interno de una empresa orientada a la venta de insumos médicos donde realice diferentes aplicaciones
  macros de excel, así como el desarrollo de una aplicación web para mostrar de que trataba la empresa a los potenciales clientes, aparte de ajustar todo lo referente a la
  parte técnica de la configuración de equipos, también trabaje con el sistema ERP Profit Plus.
</p>
<p>
  Luego de haber terminado con esa grandiosa experiencia, inicié trabajo con la empresa misabogadoss C.A. en donde me dieron el cargo de analista y desarrollador web, realizando
  una aplicación web en donde la funcionalidad principal es la de un directorio de abogados para su consulta a posterior por parte de los usuarios, un front-end para la búsqueda del
  los abogados así como de noticias legales y todo lo referente al ámbito.
</p>
<p>
  En esta misma empresa me tocó enseñar todo lo referente a el framework KumbiaPHP, que anteriormente me tocó aprender y por su baja curva de aprendizaje desarrolle aplicaciones robustas
  en cuestión de minutos literalmente entre 30 y 45 minutos, luego de haber entrenado a un equipo en dicho framework empezamos a realizar diferentes proyectos que nos llegaban a las
  manos para ser desarrolladas en poco tiempo y de forma excelente según lo acordado con el cliente, Framework es rapidez, y alivio al corazón de un programador, luego de un tiempo conocimos
  Laravel para aplicaciones web, ya que era el tema del momento y que los clientes exigían nos tocó aprender mucho de el, puedo decir que entre el Composer y Artisan, así como sus migraciones
  realizar una aplicación web fue cada vez más rápido y robusto.
</p>
<p>
  Muchas de las aplicaciones que realizamos eran con un front-end y backend básico a modo de gestor de contenidos, así como me tocó desarrollar aplicaciones web únicas debido a que lo que exigían
  era algo fuera de lo usual como la gestión de llenado de clientes de una empresa de prestamos para vehículos, impresión del contrato a través de la web, uso de PDF para obtener reportes, así como
  el control de pago de cuotas, reintegros, observaciones de clientes, sin embargo para todo hay una solución, también me toco desarrollar en una aplicacion web donde estaba un directorio médico para
  que los usuarios puedan pautar citas online sin llegar fisicamente al lugar del consultorio del médico, un perfil completo del médico, así como un buscador según la especialidad del médico.
</p>
  </div>
  <div class="tab-pane fade" id="finales">
    <p>Los sitios web que he realizado y participado en el proyecto son:
    	<ul>
    	   <li>www.misgalenos.net - Directorio de médicos en línea</li>
    	   <li>www.citycars.com.ve - Empresa de financiamiento</li>
    	   <li>www.oceancars.com.ve - Empresa de prestamos y compra de vehículos</li>
    	   <li>www.yickson.com.ve - Sintesís curricular en web</li>
    	   <li>www.ideasmillonarias.com.ve - Ideas sobre como invertir en Internet</li>
    	</ul>
    	Los sitios web en los cuales he gestionado como administrador y desarrollador de la web son los siguientes:
    	<ul>
           <li>www.prodimic.net - Empresa que comercia con plantas eléctricas Kipor</li>
           <li>www.hyperelectricos.com - Empresa que vende todo lo referente a materiales eléctricos</li>
    	</ul>
    	Cursos realizados con certificados:
    	<ul>
    	   <li>Marketing Digital</li>
    	   <li>Programación orientada a Objetos</li>
    	   <li>Ensamblaje y mantenimiento de PC</li>
    	   <li>Analítica web</li>
    	   <li>Desarrollo web HTML y CSS</li>
    	   <li>Cloud Computing</li>
    	   <li>Productividad personal</li>
    	   <li>Comercio electrónico</li>
    	</ul>
    	Aunque no toda mi carrera ha girado en torno a la programación también he tenido la labor de ser soporte
    	técnico de diversas empresas, haciendo un mantenimiento preventivo y correctivo a los equipos que me ha
    	tocado gestionar de forma eficiente, así como enseñar aplicaciones como lo son Outlook para el manejo de 
    	correos empresariales, así como lo es Thunderbird, y aplicaciones web para gestión de tareas laborables como
    	Google Calendar, así como también he apoyado a las empresas en la parte de manejo correcto de las redes
    	sociales Facebook, Twitter, y SEO mediante la herramienta de Google Analytics.
    </p>
    <p>Algunos scripts: <a href="/varios">Ver Scripts</a></p>
  </div>
</div>
</div>
<div class="col-lg-2"></div>