<!DOCTYPE html>
<html lang="es">
 <head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
 
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Backend de Yickson</title>
  <?php Tag::css('readable') ?>
  <?php Tag::css('font') ?>
  <?php Tag::css('style') ?>
  <?php echo Html::includeCss() ?>
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-3"></div>

      <div class="col-xs-12 col-sm-6 col-md-6">
      <h2 class="text-center">Yickson en su rincón</h2>
      <h3 class="text-center">Sistema de control</h3>
      </div>
      <div class="col-sm-3 col-md-3"></div>
    </div>
    <?php View::content(); ?>
    <?php View::partial('pie') ?>
</div>
<?php echo Tag::js('jquery'); ?>
<?php echo Tag::js('bootstrap'); ?>
</body>
</html>
